const disciplinas = [
  "Administração de Sistemas de Redes",
  "Algoritmos e Programação A",
  "Algoritmos e Programação B",
  "Cálculo B",
  "Eletromagnetismo e Propagação",
  "Eletricidade Básica",
  "Estatística",
  "Estatística Para Pesquisa",
  "Estrutura de Dados",
  "Fundamentos da Computação",
  "Fundamentos da Matemática",
  "Fundamentos de Computação",
  "Gerenciamento de Infraestrutura de Ti",
  "Governança de Tecnologia da Informação",
  "Governança de Ti",
  "Grafos em Redes",
  "Interconexão de Redes",
  "Interconexões de Redesw",
  "Introdução a Redes de Computadores",
  "Introdução à Segurança",
  "Laboratório de Sistemas Operacionais",
  "Organização e Arquitetura de Computadores",
  "Organização e Arquitetura de Computadores A",
  "Organização e Arquitetura de Computadores B",
  "Pesquisa Aplicada",
  "Projeto de Redes",
  "Protocolos de Aplicação",
  "Relações Humanas e Diversidade",
  "Redes Aplicadas a Telecomunicações",
  "Redes Sem Fio",
  "Segurança em Redes de Computadores",
  "Sistemas de Cabeamento Estruturado",
  "Sistemas Digitais",
  "Sistemas Distribuídos",
  "Sistemas Operacionais",
  "Tecnologia de Comunicação de Dados",
  "Tecnologia de Redes Industriais",
  "Tecnologias Para Infraestruturas Virtualizadas",
  "Qualquer Semestre",
];

export default disciplinas;